[
	{	
		"type":"warning",
		"ip":"vps62061.vps.ovh.ca:443",
		"gamemode":"Juggernaut",
		"region":"Play",
		"bot":"Packet errors :( - semiworking"
	},
	{	
		"type":"success",
		"ip":"play.flipsidetech.com:443",
		"gamemode":"FFA",
		"region":"Play",
		"bot":"WORKING"
	},
	{	
		"type":"info",
		"ip":"parisgamma.iomods.com:1501",
		"gamemode":"FFA [PARISGAMMA]",
		"region":"Play",
		"bot":"WORKING"
	},
	{	
		"type":"info",
		"ip":"75.74.28.26:3005",
		"gamemode":"FFA",
		"region":"Play",
		"bot":"WORKING"
	}
]
